steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ai-persona-backend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ai-persona-backend:latest'
      - '.'

  # Docker イメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ai-persona-backend:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ai-persona-backend:latest'

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-persona-backend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ai-persona-backend:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_PROJECT_ID=${PROJECT_ID},CORS_ORIGIN=${_FRONTEND_URL}'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--port'
      - '8080'
      - '--cpu'
      - '1'
      - '--memory'
      - '2Gi'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: ai-persona-repo
  _FRONTEND_URL: https://your-frontend-url.vercel.app

timeout: 1200s 